<a href="https://colab.research.google.com/github/zmgy107/Pytorch-Learning-Notes/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# Initializing a Tensor

**Directly from data**

Tensors can be created directly from data. The data type is automatically inffered

In [ ]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
# print(x_data)

**From a NumPy array**

Tensors can be created from NumPy arrays.

In [ ]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print("np_array:",np_array)
print("x_np:",x_np)

np_array: [[1 2]
 [3 4]]
x_np: tensor([[1, 2],
        [3, 4]])


**From another tensor**

The new tensor retains the properties(shape,datatype) of the argument tensor,unless explicitly overridden.

In [ ]:
x_ones=torch.ones_like(x_data) # retains tthe properties of x_data
print(f"Ones Tensor:\n{x_ones}\n")

x_rand=torch.rand_like(x_data,dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor:\n{x_rand}\n")

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.0921, 0.3246],
        [0.6251, 0.3121]])



**With random or constant values:**

shape is a tuple of tensor dimensions.In the functionns below,it determines the dimensionality of the output tensor.

In [ ]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tensor:\n{zeros_tensor}")

shape_1=(2,3,4)
threes_tensor=3*torch.ones(shape_1)
print("Threes_tensor:\n",threes_tensor)
# shape(n,m,k) 返回由n个列表构成的元组，每个列表由m个子列表构成，每个子列表由元素个数为k的列表

Random Tensor:
tensor([[0.7025, 0.2520, 0.0922],
        [0.4502, 0.3191, 0.7902]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Threes_tensor:
 tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]])


# Attributes of a Tensor

Tensor attributes describe their shape,datatype,and the device on which they are stored

In [ ]:
tensor=torch.rand(3,4)

print(f"Shape of tensor:{tensor.shape}")
print(f"DataType of tensor:{tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device}")

Shape of tensor:torch.Size([3, 4])
DataType of tensor:torch.float32
Device tensor is stored on:cpu


# Operations on Tensors

tensor operations:arithmetic,linear algebra,matric manipulation(transposing,indexing,slicing),sampling and more

By default,tensors are created on the CPU.We need to explicitly move tensors to GPU using 

```
# .to
```
method(after checking for GPU availability).


In [ ]:
# move tensor to the GPU if available
if torch.cuda.is_available():
  tensor=tensor.to("cuda")

try some operations

**Standard numpy-like indexing and slicing:**

In [ ]:
tensor=torch.ones(4,4)
print(f"First row:{tensor[0]}")
print(f"First column:{tensor[:,0]}")
print(f"Last column:{tensor[...,-1]}")
tensor[:,1]=2
print(tensor)

First row:tensor([1., 1., 1., 1.])
First column:tensor([1., 1., 1., 1.])
Last column:tensor([1., 1., 1., 1.])
tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])


**Joining tensors**

use torch.cat to concatenate a sequence of tensors along a given dimension

In [ ]:
t1=torch.cat([tensor,tensor],dim=1)
print(t1)

# Dimension out of range (expected to be in range of [-2, 1])
t2=torch.cat([tensor,tensor],dim=-2)
print(t2)

tensor([[1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1.]])
tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])


**Arithmetic operations**

In [ ]:
# This computes the matrix multiplication between two tensors.
# tensor.T returns the transpose of a tensor
y1=tensor @ tensor.T
print("y1",y1)

y2=tensor.matmul(tensor.T)
print("y2",y2)

y3=torch.rand_like(y1)
# print("y3",y3)
torch.matmul(tensor,tensor.T,out=y3)
print("y3",y3)

# y4 should define first.And it's better to set same dimension of output
# y4=torch.rand(2,2) 
# torch.matmul(tensor.T,tensor,out=y4)
# print("y4",y4)


# This computes the element-wise product.矩阵间对应位置元素相乘
z1=tensor*tensor
z2=tensor.mul(tensor)

z3=torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

print(f"z1:{z1}")
print(f"z2:{z2}")
print(f"z3:{z3}")

y1 tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
y2 tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
y3 tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
z1:tensor([[1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.]])
z2:tensor([[1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.]])
z3:tensor([[1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.]])


**Single-element tensors**

If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [ ]:
agg=tensor.sum()
print(f"agg:{agg}",type(agg))
# .item的作用是将一维的tensor转变类型为数值型
agg_item=agg.item()
print(agg_item,type(agg_item))

agg:20.0 <class 'torch.Tensor'>
20.0 <class 'float'>


**In-place operations**

Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [ ]:
print(f"{tensor}\n")
tensor.add_(2)
print(tensor)

#x.copy_(y) 把y复制给x
tensor_copy=torch.rand_like(tensor)
#tensor_copy=torch.rand(2,3) The size of tensor a must match the size of tensor b 
print(f"Previous:\n{tensor_copy}")
tensor_copy.copy_(tensor)
print(f"After copying:\n{tensor_copy}")


# x.t_() to tensor 转置
tensor.t_()
print(tensor)

tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])

tensor([[3., 4., 3., 3.],
        [3., 4., 3., 3.],
        [3., 4., 3., 3.],
        [3., 4., 3., 3.]])
Previous:
tensor([[0.0865, 0.1951, 0.2321, 0.4184],
        [0.1034, 0.4632, 0.3489, 0.6807],
        [0.1315, 0.8060, 0.0139, 0.4755],
        [0.2423, 0.2225, 0.9654, 0.1262]])
After copying:
tensor([[3., 4., 3., 3.],
        [3., 4., 3., 3.],
        [3., 4., 3., 3.],
        [3., 4., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**Note**

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

# Bridge with Numpy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

Tensor to NumPy array

In [ ]:
t=torch.ones(5)
print(f"t:{t}")
n=t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [ ]:
t.add_(2)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([3., 3., 3., 3., 3.])
n:[3. 3. 3. 3. 3.]


NumPy array to Tensor

In [ ]:
n=np.ones(5)
t=torch.from_numpy(n)

# Changes in the NumPy array reflects in the tensor.
np.add(n,5,out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
n: [6. 6. 6. 6. 6.]
